# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Treasure Trove
email: buck.kerswell@gmail.com
description: Boise Area Cycling Routes
baseurl: /treasure-trove # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site

# Logo settings
logo-image-url: assets/images/logo.svg
font-awesome-icon-logo:

# Social settings
github_username: buchanankerswell
website: https://buchanankerswell.com
phone: (480) 417-2797

# Build settings
markdown: kramdown

# Layout settings
home-link-in-menu: yes
